name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: chesnokovtest
          url: https://gitlab.com/chesnokovtest/obsidian.git
          # Personal access token from gitlab.com 
          token: glpat-eVxf_gkgaEQzLXpLeKnZ
